Fix link redirects - master
conan-io/docs pull request #1892
Opened 2020-10-23 14:59 UTC by danimtb

2020-10-23 15:47 UTC, czoido requested changes
Looks like there are some broken links

2020-10-23 16:03 UTC, danimtb commented
u r mk  me sad 😢

2020-10-23 16:10 UTC, czoido commented
> u r mk me sad 😢

🤣

2020-10-26 09:15 UTC, danimtb commented
working!

2020-10-26 09:19 UTC, merged