- update docs for MesonToolchain and Meson (build helper)
conan-io/docs pull request #1980
Opened 2021-01-12 17:48 UTC by SSE4

closes: #1975 

docs for:
https://github.com/conan-io/conan/pull/8147
https://github.com/conan-io/conan/pull/8111

2021-01-12 17:55 UTC, czoido commented on creating_packages/toolchains/meson.rst
>  ``conan_meson_native.ini`` will contain the definitions of all the Meson properties
Shouldn't this be?:
```suggestion
``conan_meson_native.ini`` or ``conan_meson_cross.ini`` will contain the definitions of all the Meson properties
```

2021-01-12 18:05 UTC, czoido approved these changes

2021-01-12 18:06 UTC, czoido commented on creating_packages/toolchains/meson.rst
> +Runs project's tests. Equivalent to running :command:`meson test -v -C .` in the build folder..
```suggestion
Runs project's tests. Equivalent to running :command:`meson test -v -C .` in the build folder.
```

2021-01-19 11:39 UTC, danimtb commented on creating_packages/toolchains/meson.rst
> +``conan_meson_cross.ini``, if doing a cross build (:ref:`cross_building_reference`).
```suggestion
built in the cache): *conan_meson_native.ini*, if doing a native build, or
*conan_meson_cross.ini*, if doing a cross-build (:ref:`cross_building_reference`).
```

2021-01-19 11:39 UTC, danimtb commented on creating_packages/toolchains/meson.rst
> +as processor architecture).
```suggestion
*conan_meson_cross.ini* contains the same information as *conan_meson_native.ini*,
but with additional information to describe host, target, and build machines (such
as the processor architecture).
```

2021-01-19 11:39 UTC, danimtb commented on creating_packages/toolchains/meson.rst
> + (native builds) or ``--cross-file conan_meson_cross.ini`` (cross builds).
```suggestion
Calls :command:`meson`, with the given generator and passing either :command:`--native-file conan_meson_native.ini`
(native builds) or :command:`--cross-file conan_meson_cross.ini` (cross builds).
```

2021-01-19 12:15 UTC, memsharded requested changes
All new toolchains and helpers are documented in reference -> conanfile -> tools, as ``conan.tools.meson`` in this case.

2021-01-19 12:23 UTC, SSE4 commented
> All new toolchains and helpers are documented in reference -> conanfile -> tools, as `conan.tools.meson` in this case.

as I can see `MakeToolchain`, `MSBuildToolchain`, `CMakeToolchain` are documented in `creating packages` -> `toolchain`

2021-01-19 12:30 UTC, memsharded commented
> as I can see MakeToolchain, MSBuildToolchain, CMakeToolchain are documented in creating packages -> toolchain

@SSE4 

Those were there before creating the new ``conan.tools.xxx`` spaces. They are gradually being moved from there to the reference. Please move the Meson one there as well.

2021-01-19 13:01 UTC, SSE4 commented on reference/conanfile/tools/meson.rst
> +``conan_meson_cross.ini``, if doing a cross build (:ref:`cross_building_reference`).
```suggestion
built in the cache): *conan_meson_native.ini*, if doing a native build, or
*conan_meson_cross.ini*, if doing a cross-build (:ref:`cross_building_reference`).
```

2021-01-19 13:02 UTC, SSE4 commented on reference/conanfile/tools/meson.rst
> +as processor architecture).
```suggestion
*conan_meson_cross.ini* contains the same information as *conan_meson_native.ini*,
but with additional information to describe host, target, and build machines (such
as the processor architecture).
```

2021-01-19 13:03 UTC, SSE4 commented on reference/conanfile/tools/meson.rst
> + (native builds) or ``--cross-file conan_meson_cross.ini`` (cross builds).
```suggestion
Calls :command:`meson`, with the given generator and passing either :command:`--native-file conan_meson_native.ini`
(native builds) or :command:`--cross-file conan_meson_cross.ini` (cross builds).
```

2021-01-19 14:57 UTC, memsharded approved these changes
Please fix the import and can be merged

2021-01-19 14:57 UTC, memsharded commented on reference/conanfile/tools/meson.rst
> +    from conans import Meson
Wrong import: ``from conan.tools.meson import Meson``

2021-01-19 15:03 UTC, SSE4 commented on reference/conanfile/tools/meson.rst
> +    from conans import Meson
```suggestion
    from conan.tools.meson import Meson
```

2021-01-19 15:21 UTC, merged