add video conan in practice
conan-io/docs pull request #2093
Opened 2021-05-02 00:20 UTC by solvingj

2021-05-04 07:47 UTC, lasote commented on videos.rst
> +      <iframe width="560" height="315" src="" frameborder="0" allow="autoplay; encrypted-media; allowfullscreen>
Is it a valid link or...?

2021-05-04 17:06 UTC, memsharded requested changes
Seems missing link, please check @solvingj

2021-05-04 17:07 UTC, solvingj commented
I see, will fix ASAP

2021-05-04 17:32 UTC, solvingj commented
Please review @memsharded @lasote

2021-05-04 18:20 UTC, uilianries commented
Jenkins is angry because Bintray is still listed in Docs.

2021-05-04 18:20 UTC, uilianries approved these changes
![Screenshot_2021-05-04 Videos and links — conan 1 36 0 documentation](https://user-images.githubusercontent.com/4870173/117050910-4f710b80-acec-11eb-955f-954fd2a24b65.png)

2021-05-05 09:53 UTC, memsharded approved these changes

2021-05-05 12:59 UTC, uilianries commented
Let's rebuild, as #2094 has been merged

2021-05-05 13:18 UTC, uilianries commented
Need to rebase

2021-05-05 13:30 UTC, solvingj commented
Isn't there normally a github button for that? I dont see it here.

2021-05-05 13:36 UTC, uilianries commented
Nope, only local git commands, not even github CLI offers rebase feature.

2021-05-05 18:11 UTC, solvingj commented
rebased onto current master, lets see how it goes.

2021-05-05 18:44 UTC, uilianries commented
I would say to target this PR into master branch.

2021-05-05 19:04 UTC, solvingj commented
Sorry, please let this be the last thing lol

2021-05-06 13:33 UTC, solvingj commented
@czoido is there anything we can do so our CI never fails with this again?

```
(line   50) broken    https://github.com/conan-io/examples/tree/master/features - 429 Client Error: too many requests for url: https://github.com/conan-io/examples/tree/master/features
(line    6) broken    https://github.com/plougher/squashfs-tools - 429 Client Error: too many requests for url: https://github.com/plougher/squashfs-tools
(line  112) broken    https://github.com/lasote/clion-conan-consumer - 429 Client Error: too many requests for url: https://github.com/lasote/clion-conan-consumer
(line  229) broken    https://github.com/lasote/clion-conan-package - 429 Client Error: too many requests for url: https://github.com/lasote/clion-conan-package
```

2021-05-06 13:48 UTC, merged