Docs about properties updates and some guidelines for migration
conan-io/docs pull request #2316
Opened 2021-12-02 17:21 UTC by czoido

2021-12-02 17:32 UTC, czoido commented on reference/conanfile/attributes.rst
> +New properties defined for for *CMake* generators family, used by :ref:`CMakeDeps<CMakeDeps>` generator:
```suggestion
New properties defined for *CMake* generators family, used by :ref:`CMakeDeps<CMakeDeps>` generator:
```

2021-12-02 17:34 UTC, czoido commented on reference/conanfile/attributes.rst
> +as the ``.names`` attribute did. With the ``.names`` attribute if you set a name for the
```suggestion
as the ``.names`` attribute did. With the ``.names`` attribute, if you set a name for the
```

2021-12-02 17:35 UTC, czoido commented on reference/conanfile/attributes.rst
> +name you set with this property will the the one that is added to the CMake generated
```suggestion
name you set with this property will be the one that is added to the CMake generated
```

2021-12-02 18:59 UTC, memsharded approved these changes

2021-12-03 08:18 UTC, lasote commented on reference/conanfile/attributes.rst
> +Using ``names``, ``filenames`` and ``build_modules`` will not work any more for new
```suggestion
Using ``.names``, ``.filenames`` and ``.build_modules`` will not work any more for new
```

2021-12-03 08:29 UTC, lasote requested changes
I would try to move some content to the CMakeDeps page and others to the migration page.

2021-12-03 08:29 UTC, lasote commented on reference/conanfile/attributes.rst
> +It is important to note that ``cmake_target_name`` is **not** goint to take the same value
```suggestion
It is important to note that ``cmake_target_name`` is **not** going to take the same value
```

2021-12-03 08:29 UTC, lasote commented on reference/conanfile/attributes.rst
> +Using ``names``, ``filenames`` and ``build_modules`` will not work any more for new
```suggestion
Using ``.names``, ``.filenames`` and ``.build_modules`` will not work any more for new
```

2021-12-03 08:30 UTC, czoido commented
This section has grown too much, I will try to reorganize these contents, maybe moving parts to the migrations section.

2021-12-03 11:15 UTC, memsharded approved these changes
It is good, but I would move the ``.. _conanv2_properties_model:`` section to its own page under "conan2migration" subfolder or something. Too heavy for something that many users at companies do not care about (mostly for ConanCenter)

2021-12-03 11:15 UTC, memsharded commented on conan_v2.rst
> +        self.cpp_info.components.names["cmake_find_package"] = "myname::myname"
Legacy way?

2021-12-03 11:42 UTC, memsharded approved these changes

2021-12-03 11:42 UTC, lasote approved these changes

2021-12-03 11:45 UTC, merged