Remove warning about dependencies bug
conan-io/docs pull request #2391
Opened 2022-02-04 17:30 UTC by uilianries

closes #2384

2022-02-21 07:03 UTC, SSE4 approved these changes

2022-02-21 18:37 UTC, memsharded requested changes
I think we want to keep the (normal) ``experimental`` note. It is not that we are declaring ``self.dependencies`` stable. We can remove the "very" and the "some bugs"

2022-02-22 09:06 UTC, uilianries commented
Done, new preview:

![Screenshot 2022-02-22 at 10-05-02 Dependencies — conan 1 45 0 documentation](https://user-images.githubusercontent.com/4870173/155098917-59851778-5e41-47ca-8566-39ae294b697f.png)

2022-02-22 09:35 UTC, memsharded approved these changes

2022-02-22 12:21 UTC, merged