Explore adding tab support for code examples...
conan-io/docs pull request #2410
Opened 2022-02-22 15:29 UTC by czoido

2022-02-22 20:44 UTC, memsharded requested changes
Good for me, but I would bring this ONLY for ``develop2``, not to master.

2022-02-23 07:25 UTC, czoido commented
> Good for me, but I would bring this ONLY for `develop2`, not to master.

But can we update the requirements to support this in master even if we just use that for develop2?
Using different requirements for different branches can complicate the ci...

2022-02-23 09:20 UTC, memsharded commented
> But can we update the requirements to support this in master even if we just use that for develop2?
Using different requirements for different branches can complicate the ci...

Yes, yes, of course, I didn't think of that, I was concerned that someone would want to add tabs to 1.X docs.

2022-02-23 09:20 UTC, memsharded approved these changes

2022-02-23 16:51 UTC, merged