Reference of tools.build and tools.files
conan-io/docs pull request #2531
Opened 2022-05-11 11:03 UTC by lasote

2022-05-11 11:41 UTC, czoido approved these changes

2022-05-11 21:24 UTC, memsharded requested changes

2022-05-11 21:24 UTC, memsharded commented on reference/tools/files/basic.rst
> +    from conans import tools
Wrong import and usage

2022-05-11 21:24 UTC, memsharded commented on reference/tools/files/basic.rst
> +        self.cpp_info.libs = tools.collect_libs(self)
Wrong usage

2022-05-11 21:24 UTC, memsharded commented on reference/tools/files/downloads.rst
> +    from conans import tools
Wrong import

2022-05-11 21:24 UTC, memsharded commented on reference/tools/files/downloads.rst
> +        tools.ftp_download('ftp.debian.org', "debian/README")
Wrong usage

2022-05-11 21:24 UTC, memsharded commented on reference/tools/files/packaging.rst
> +        from conans import ConanFile
```suggestion
        from conan import ConanFile
```

2022-05-12 07:38 UTC, memsharded approved these changes

2022-05-12 10:23 UTC, merged