cppstd ported tools
conan-io/docs pull request #2616
Opened 2022-06-28 14:55 UTC by lasote

https://github.com/conan-io/conan/pull/11446/files

2022-06-28 16:48 UTC, SSE4 commented on reference/conanfile/tools/build.rst
> +        4. If can not detect the default cppstd for settings.compiler, a exception will be raised.
@franramirez688 
> What do you mean with can not detect the default cppstd for settings.compiler

you always can detect default cppstd for the compiler - compiler defined `__cplusplus` macro to the appropriate value.
if it doesn't, it means compiler is very ancient and predates even C++98.

> Could you provide a ref for cppstd_default? is it the function below?

do you mean `RREF` or `PREF`? anyway, I don't see a point providing it into the `cppstd_default`

> Which is the minimal version required? Is it defined by the points above?

the minimum version required is the minimum version required to compile the code successfully. e.g. if code uses `constexpr`, minimum version cannot be less that C++11, but if it uses `consteval`, it cannot be less that C++20. in general, it's something hard to detect without trial and error.

2022-06-28 21:02 UTC, memsharded requested changes

2022-06-28 21:02 UTC, memsharded commented on reference/conanfile/tools/build.rst
> +conan.tools.build.default_cppstd
This method is not tested, and it seems broken in code. Better not document it atm.

2022-06-29 06:56 UTC, franramirez688 approved these changes

2022-06-29 07:03 UTC, SSE4 approved these changes

2022-06-29 07:41 UTC, merged