[bug] get_cpus is not supporting cgroup2 #11635
conan-io/docs pull request #2658
Opened 2022-07-25 17:26 UTC by MariaMozgunova

Docs for: https://github.com/conan-io/conan/pull/11667

Documents the changes made for the cgroupv2 support in the `cpu_count()` function.

2022-07-25 17:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/docs?pullRequest=2658) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/docs?pullRequest=2658) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/docs?pullRequest=2658) it.</sub>

2022-07-25 17:34 UTC, SSE4 approved these changes

2022-07-26 08:14 UTC, memsharded requested changes
This documentation is not completely in the right place, because the changes were done to the new tool in ``from conan.tools``, no in this one which is the legacy ``from conans`` one.

It needs to be documented in https://docs.conan.io/en/latest/reference/conanfile/tools/build.html, as the ``build_jobs`` helper and the new ``conf``.

This is not this PR fault, but this was missing before, sorry about that.

2022-07-27 17:15 UTC, memsharded approved these changes

2022-07-27 17:16 UTC, merged