Fixes #14166: Add strip docs to cmake.install
conan-io/docs pull request #3281
Opened 2023-06-25 18:55 UTC by sagi-ottopia

2023-06-25 18:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/docs?pullRequest=3281) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/docs?pullRequest=3281) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/docs?pullRequest=3281) it.</sub>

2023-07-06 08:39 UTC, memsharded requested changes
This is outdated now to https://github.com/conan-io/conan/pull/14167

Thanks for contributing the docs too!

2023-07-08 05:05 UTC, sagi-ottopia commented
Hi, I would like to update the docs according to the change that I made.
Where do you think is the most appropriate docs/section for it ?
Sagi

2023-07-08 19:42 UTC, memsharded commented
https://docs.conan.io/1/reference/conanfile/tools/cmake/cmake.html#install would be good.

I have just merged develop -> release/2.0, so this will be in next 2.0.8 too

2023-07-09 22:04 UTC, memsharded approved these changes

2023-07-09 22:05 UTC, merged