cmake: Add mentioning of tools.cmake:install strip
conan-io/docs pull request #3314
Opened 2023-07-30 10:33 UTC by mkmkme

I noticed there was no mentioning of this configuration in the docs. This commit fixes that.

2023-08-07 07:39 UTC, uilianries approved these changes

2023-08-07 07:45 UTC, memsharded commented
Thanks for the contribution. The merged PR belongs to 2.0.10, still not released: https://github.com/conan-io/conan/pull/14397, (check the milestone)

That means this PR should go to ``develop2`` branch instead, because if it is merged in the ``release/2.0`` branch in the docs, it goes live. (sorry about that, we know the branches in docs and client repos are not fully aligned, we will fix it for future 2.X train release)

2023-08-07 07:46 UTC, memsharded requested changes
Seems targeting ``develop2`` branch caused some unwanted commits, sorry for the issues.

2023-08-28 10:28 UTC, czoido approved these changes

2023-08-28 10:28 UTC, merged