New docs for `conan version`
conan-io/docs pull request #3691
Opened 2024-04-19 10:41 UTC by ErniGH

https://github.com/conan-io/conan/pull/16102

2024-04-20 20:51 UTC, RubenRBS requested changes

2024-04-20 20:51 UTC, RubenRBS commented on reference/commands/version.rst
> +            "sys_executable": "/Users/myUser/Documents/GitHub/conan/venv/bin/python",
```suggestion
            "sys_executable": "/conan/venv/bin/python",
```

2024-04-20 20:51 UTC, RubenRBS commented on reference/commands/version.rst
> +      sys_executable: /Users/myUser/Documents/GitHub/conan/venv/bin/python
```suggestion
      sys_executable: /conan/venv/bin/python
```

2024-04-20 20:51 UTC, RubenRBS commented on reference/commands/version.rst
> +    conan_path: /Users/myUser/Documents/GitHub/conan/venv/bin/conan
```suggestion
    conan_path: /conan/venv/bin/conan
```

2024-04-22 11:28 UTC, RubenRBS approved these changes

2024-04-22 14:12 UTC, czoido approved these changes

2024-04-22 14:12 UTC, merged