Update Android Studio documentation
conan-io/docs pull request #3847
Opened 2024-09-19 16:28 UTC by perseoGI

Newer versions of Android Studio, by default select `kotlin` as the `Build configuration language`.

This PR introduces a new sphinex plugin which supports code tabs, used to display both configurations:
- Groovy 
- Kotlin

2024-09-19 19:27 UTC, AbrilRBS commented
If this is something that we end up using, there are some places in the codebase where the tab could be useful for the Linux vs Windows command syntax

2024-09-20 08:12 UTC, perseoGI commented
@AbrilRBS yes, definitely!

2024-09-20 10:04 UTC, danimtb approved these changes

2024-09-20 10:38 UTC, czoido requested changes
This should go to the release/2.7 branch if the changes are not related with the 2.8.0 release. Also the changes merged to that branch are immediately published.

2024-09-22 17:35 UTC, memsharded commented on examples/cross_build/android/android_studio.rst
> +         .. code-tab:: text Conan Packed NDK
```suggestion
         .. code-tab:: text Conan NDK package
```

2024-09-24 08:54 UTC, czoido approved these changes

2024-09-24 08:54 UTC, merged